### ISSUE TITLE
It's Just Sleeping?

### ISSUE THREAD

**Issue by dolang** [pypa/wheel-builders#3]
Hi,

I'm sure you guys are busy with other things right now, with all the work around PyPI, but I'm in the process of learning how to properly build `manylinux1` packages and I have a few questions.

The first one being: Is this repository "just sleeping" and has since been abandoned for something else? If so, where should I look? The mailing list isn't all that active either.

**Comment by methane** [comment]
You should see https://packaging.python.org/

**Comment by njsmith** [comment]
It turned out that this repo has never been used for much.

packaging.python.org is a good general packaging overview, but last time I looked it didn't have much about manylinux wheels yet.

If you have questions it doesn't answer, I'd suggest sending questions to the wheel-builders or distutils-sig mailing lists.
